batch_size: 128
epochs: 20
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data
image_dir: data
clip_checkpoint_dir: data
clip_model_dir: data
checkpoint_dir: data
model_dir: data
brain_to_clip_path: data/brain_to_clip_checkpoint_epoch_20.pt

# Evaluation
model_path: 
